name: GitHub SecondPipelien
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    artifact-download:
        runs-on: ubuntu-latest
        steps:
        - name: downalod a file
          uses: actions/download-artifact@v4
          with:
            name: output-log-file